name: Check

on: [push, pull_request]

jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        emacs-version:
          - 27.1
          - 27.2
          - 28.1
        elisp-check:
          - melpa
          - load-file
          - byte-compile
          - checkdoc
          - package-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: leotaku/elisp-check@v1.1
        with:
          check: ${{ matrix.elisp-check }}
          file: "org-fragtog.el"
